global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "rabithr-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "rabithr-app"
    static_configs:
      - targets: ["app:3000"]
    metrics_path: "/metrics"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "mysql"
    static_configs:
      - targets: ["db:3306"]
